inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6

GetText:
  Enabled: false

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

RailsI18n:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

RSpec:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'

Performance/CaseWhenSplat:
  Enabled: true

Performance/OpenStruct:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DocumentationMethod:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringHashKeys:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/OptionHash:
  Enabled: true
